Debug: verify ipa location and validate build

diff --git a/.github/workflows/Apple_Test_Deployment.yml b/.github/workflows/Apple_Test_Deployment.yml
--- a/.github/workflows/Apple_Test_Deployment.yml
+++ b/.github/workflows/Apple_Test_Deployment.yml
@@ -76,12 +76,26 @@ jobs:
           echo "Uploading build $buildName"
           flutter build ipa --release --version --build-number=$buildNumber --build-name=$buildName --export-options-plist=macos/ExportOptions.plist
 
+      - name: List IPA Directory Contents
+        run: ls -la build/ios/ipa/        
+
       - name: Upload IPA to TestFlight
         run: |
-          APP_FILE=$(find $(pwd) -name "*.ipa")
+          APP_FILE=$(find $(pwd)/build/ios/ipa -name "*.ipa")
+          if [ -z "$APP_FILE" ]; then
+            echo "Error: .ipa file not found!"
+            exit 1
+          fi
+          
+          xcrun altool --validate-app \
+          --type ios \
+          --file "$APP_FILE" \
+          --apiKey ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }} \
+          --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
+
           xcrun altool --upload-app \
             --type ios \
-            -f "$APP_FILE" \
+            --file "$APP_FILE" \
             --apiKey ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }} \
             --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
         
