show all folders available immediately after build

diff --git a/.github/workflows/Apple_Test_Deployment.yml b/.github/workflows/Apple_Test_Deployment.yml
--- a/.github/workflows/Apple_Test_Deployment.yml
+++ b/.github/workflows/Apple_Test_Deployment.yml
@@ -75,29 +75,30 @@ jobs:
           buildName="${versionValue[0]}.${versionValue[1]}.${{ github.run_number }}"
           echo "Uploading build $buildName"
           flutter build ipa --release --version --build-number=$buildNumber --build-name=$buildName --export-options-plist=macos/ExportOptions.plist
+          ls -la
 
-      - name: List IPA Directory Contents
-        run: |
-            ls -la build/ios/archive/
-            # ls -la build/ios/ipa/        
+      # - name: List IPA Directory Contents
+      #   run: |
+      #       ls -la build/ios/archive/
+      #       # ls -la build/ios/ipa/        
 
-      - name: Upload IPA to TestFlight
-        run: |
-          APP_FILE=$(find $(pwd)/build/ios/ipa -name "*.ipa")
-          if [ -z "$APP_FILE" ]; then
-            echo "Error: .ipa file not found!"
-            exit 1
-          fi
+      # - name: Upload IPA to TestFlight
+      #   run: |
+      #     APP_FILE=$(find $(pwd)/build/ios/ipa -name "*.ipa")
+      #     if [ -z "$APP_FILE" ]; then
+      #       echo "Error: .ipa file not found!"
+      #       exit 1
+      #     fi
 
-          xcrun altool --validate-app \
-          --type ios \
-          --file "$APP_FILE" \
-          --apiKey ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }} \
-          --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
+      #     xcrun altool --validate-app \
+      #     --type ios \
+      #     --file "$APP_FILE" \
+      #     --apiKey ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }} \
+      #     --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
 
-          xcrun altool --upload-app \
-            --type ios \
-            --file "$APP_FILE" \
-            --apiKey ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }} \
-            --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
+      #     xcrun altool --upload-app \
+      #       --type ios \
+      #       --file "$APP_FILE" \
+      #       --apiKey ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }} \
+      #       --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
         
